version: "3.7"

services:
    # App
    app:
        # Purpose: application's local environment
        container_name: app
        build:
            context: ./env
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - ./env/go:/go/pkg/mod/cache # Local cache for dependencies
        ports:
            - 8080:8080
        links:
            - db
        working_dir: /app
        env_file: ./env/.env
        command: go run cmd/main.go
    # Database
    db:
        # Purpose: application's database.
        container_name: db
        image: postgres:9.6
        volumes:
            - ./env/db/data:/var/lib/postgresql
        ports:
            - 5432:5432
        env_file: ./env/.env
    # Database GUI
    db_gui:
        # Purpose: GUI database for database.
        # Available at http://0.0.0.0:5050
        container_name: db_gui
        image: fenglc/pgadmin4:1.1
        volumes:
            - ./env/db/pgadmin4:/root/.pgadmin
        ports:
            - 5050:5050
        links:
            - db
        env_file: ./env/.env

