# syntax=docker/dockerfile:1

##########
# Project's image, for local development only.
FROM golang:1.20-alpine

ARG BUILD_DATE=now
ARG COMMIT_HASH=development

RUN apk update && \
    apk upgrade && \
    apk add --no-cache git && \
    rm -rf /var/cache/apk/*

WORKDIR /app

COPY . /app

ENV GOPROXY https://proxy.golang.org

RUN go install github.com/cespare/reflex@latest
COPY reflex.conf /

EXPOSE 8080

ENTRYPOINT ["reflex", "-c", "/reflex.conf"]
